# Generated by Django 5.2.15 on 2026-08-04 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', help_text='ユーザーが削除されても誰の操作か分かるよう、名前を控えておく。', max_length=150, verbose_name='操作者名')),
                ('action', models.CharField(choices=[('create', '作成'), ('update', '更新'), ('delete', '削除'), ('submit_review', 'レビュー依頼'), ('approve', '承認'), ('reject', '差し戻し'), ('publish', '公開'), ('unpublish', '非公開化'), ('restore', '版の復元'), ('login_failed', 'ログイン失敗')], max_length=32, verbose_name='操作')),
                ('target_app_label', models.CharField(blank=True, default='', max_length=100, verbose_name='対象アプリ')),
                ('target_model', models.CharField(blank=True, default='', max_length=100, verbose_name='対象モデル')),
                ('target_id', models.CharField(blank=True, default='', max_length=64, verbose_name='対象ID')),
                ('target_repr', models.CharField(blank=True, default='', max_length=200, verbose_name='対象の表示名')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='詳細')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='IPハッシュ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='日時')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作ログ',
                'verbose_name_plural': '操作ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_app_label', 'target_model', 'target_id'], name='core_auditl_target__c62dfd_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
