# Generated by Django 5.2.15 on 2026-08-04 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_article_featured_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='表示名')),
                ('email', models.EmailField(blank=True, default='', help_text='公開されない。連絡が必要なときだけ使う。', max_length=254, verbose_name='メールアドレス')),
                ('body', models.TextField(max_length=2000, verbose_name='本文')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('is_spam', models.BooleanField(default=False, verbose_name='スパム')),
                ('ip_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='IPハッシュ')),
                ('user_agent', models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='記事')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='投稿ユーザー')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['article', 'is_approved', 'created_at'], name='comments_co_article_aa093e_idx'), models.Index(fields=['ip_hash', 'created_at'], name='comments_co_ip_hash_d2f666_idx')],
            },
        ),
    ]
