# Generated by Django 5.2.15 on 2026-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='スラッグ')),
                ('body', models.TextField(verbose_name='本文')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('published', '公開')], default='draft', max_length=20, verbose_name='公開状態')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='フッターに表示')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '固定ページ',
                'verbose_name_plural': '固定ページ',
                'ordering': ['menu_order', 'title'],
            },
        ),
    ]
