# Generated by Django 5.2.15 on 2026-08-04 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_featured_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('publish_article', '記事を公開できる'), ('review_article', '記事のレビューを承認できる')], 'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('status', models.CharField(max_length=20, verbose_name='公開状態')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='保存日時')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='メモ')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog.article', verbose_name='記事')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_revisions', to=settings.AUTH_USER_MODEL, verbose_name='保存者')),
            ],
            options={
                'verbose_name': '記事の版',
                'verbose_name_plural': '記事の版',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='blog_articl_article_8a8396_idx')],
            },
        ),
    ]
