# Generated by Django 5.2.15 on 2026-08-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_articlerevision'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, default='', help_text='他サイトへ転載した記事など、正規のURLが別にある場合に指定する。', verbose_name='正規URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='noindex',
            field=models.BooleanField(default=False, help_text='この記事だけを検索結果に出したくない場合に有効にする。', verbose_name='検索エンジンから除外'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='空ならアイキャッチ画像、それも空ならサイト既定の画像を使う。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='og_articles', to='media_library.mediaasset', verbose_name='OG画像'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='空なら本文の冒頭を使う。', max_length=160, verbose_name='SEO説明文'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='空なら記事タイトルを使う。全角35文字程度が目安。', max_length=70, verbose_name='SEOタイトル'),
        ),
    ]
