# Generated by Django 5.2.15 on 2026-08-04 05:06

import blog.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_canonical_url_article_noindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReusableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名前')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='説明')),
                ('blocks', models.JSONField(default=list, validators=[blog.blocks.validate_blocks], verbose_name='ブロック')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '再利用ブロック',
                'verbose_name_plural': '再利用ブロック',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='blocks',
            field=models.JSONField(blank=True, default=list, validators=[blog.blocks.validate_blocks], verbose_name='本文ブロック'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='blocks',
            field=models.JSONField(blank=True, default=list, verbose_name='本文ブロック'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default='', help_text='ブロックエディターを使う場合は自動で埋まる。検索と抜粋はこの欄を対象にする。', verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='本文'),
        ),
    ]
