# Generated by Django 5.2.15 on 2026-08-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_reusableblock_article_blocks_articlerevision_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='版番号'),
        ),
    ]
