# Generated by Django 5.2.15 on 2026-08-04 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KururuCMS', max_length=100, verbose_name='サイト名')),
                ('tagline', models.CharField(blank=True, default='', max_length=200, verbose_name='キャッチコピー')),
                ('description', models.CharField(blank=True, default='', help_text='検索結果に出る既定の説明文。160文字以内。', max_length=160, verbose_name='サイト説明')),
                ('base_url', models.URLField(default='http://localhost:8000', help_text='末尾のスラッシュなし。例: https://cms.example.com', verbose_name='サイトのURL')),
                ('accent_color', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', '色は #rgb または #rrggbb の形式で指定してください。')], verbose_name='アクセント色')),
                ('accent_color_dark', models.CharField(default='#60a5fa', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', '色は #rgb または #rrggbb の形式で指定してください。')], verbose_name='アクセント色（ダーク）')),
                ('show_sidebar', models.BooleanField(default=True, verbose_name='サイドバーを表示')),
                ('sidebar_recent_count', models.PositiveSmallIntegerField(default=5, verbose_name='最新記事の表示数')),
                ('noindex_site', models.BooleanField(default=False, help_text='ステージング環境では必ず有効にする。', verbose_name='サイト全体を検索エンジンから除外')),
                ('twitter_site', models.CharField(blank=True, default='', help_text='@ を含めて入力。例: @example', max_length=50, verbose_name='X（Twitter）のアカウント')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='既定のOG画像')),
            ],
            options={
                'verbose_name': 'サイト設定',
                'verbose_name_plural': 'サイト設定',
            },
        ),
    ]
