# Generated by Django 5.2.15 on 2026-08-04 04:34

import django.db.models.deletion
import media_library.models
import media_library.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(height_field='height', upload_to=media_library.models.upload_to, validators=[media_library.validators.ImageUploadValidator()], verbose_name='ファイル', width_field='width')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='タイトル')),
                ('alt_text', models.CharField(blank=True, default='', help_text='画像が見えない利用者へ内容を伝える文章。装飾目的なら空でよい。', max_length=200, verbose_name='代替テキスト')),
                ('width', models.PositiveIntegerField(default=0, editable=False, verbose_name='幅')),
                ('height', models.PositiveIntegerField(default=0, editable=False, verbose_name='高さ')),
                ('byte_size', models.PositiveIntegerField(default=0, editable=False, verbose_name='サイズ')),
                ('image_format', models.CharField(blank=True, editable=False, max_length=10, verbose_name='形式')),
                ('checksum', models.CharField(blank=True, db_index=True, editable=False, help_text='SHA-256。同じ画像の重複アップロードを検出する。', max_length=64, verbose_name='チェックサム')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': 'メディア',
                'verbose_name_plural': 'メディア',
                'ordering': ['-created_at'],
            },
        ),
    ]
